name: fleezy
description: Fleet management made Easy

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.1.1
  firebase_auth: ^1.1.4
  cloud_firestore: ^2.1.0
  intl: ^0.17.0
  curved_navigation_bar: ^0.3.7
  flutter_spinkit: ^5.0.0
  provider: ^5.0.0
  geolocator: ^7.0.3
  google_fonts: ^2.0.0
dev_dependencies:
  pedantic: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          
