name: fleezy
description: Fleet management made Easy

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  cloud_firestore: ^1.0.6
  intl: ^0.17.0
  curved_navigation_bar: ^0.3.7
  flutter_spinkit: ^5.0.0
  provider: ^5.0.0
  location: ^4.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/dancing_script.ttf
    - family: FundamentoRegular
      fonts:
        - asset: assets/fonts/Fondamento-Regular.ttf
    - family: PlayFairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay.ttf
