name: fleezy
description: Fleet management made Easy

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  firebase_storage: ^10.1.0
  cloud_firestore: ^3.1.0
  intl: ^0.17.0
  bottom_navy_bar: ^6.0.0
  flutter_spinkit: ^5.1.0
  provider: ^6.0.1
  geolocator: ^7.7.1
  google_fonts: ^2.1.0
  image_picker: ^0.8.4+4
  # objectbox: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: RobotoCondensed
  #     fonts:
  #       - asset: assets/fonts/RobotoCondensed-Light.ttf
